### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by fitzgen**
r? @philipc or @jonhoo

### CODE REVIEW

**Comment by jonhoo** [comment]
@fitzgen any chance you could submit the rustfmt changes separately? unless the dependency bump *only* changes `Cargo.toml`...

**Comment by philipc** [comment]
@jonhoo The dependency bumps change more than `Cargo.toml`. If you're just wanting to see what those changes were, then they're already in separate commits that you can review individually.

**Comment by fitzgen** [comment]
> this doesn't fix everything in #38 though does it?

Not sure; don't have concrete steps to reproduce or test case, so can't verify myself.

> @fitzgen any chance you could submit the rustfmt changes separately? unless the dependency bump only changes Cargo.toml...

As @philipc said, they're separate commits, so if you click on the "commits" tab here (in between "Discussion" and "Files Changed", you can see each commit's change in isolation :)

**Comment by fitzgen** [comment]
Published 0.4.0 on crates.io

**Pull request merged**
