### PR TITLE
End sequence

### PR DESCRIPTION
**Pull request by fitzgen**
r? @philipc

### CODE REVIEW

**Comment by fitzgen** [comment]
Beat you to it ;)

This fixes the issues I was seeing in my ongoing work to integrate this crate into backtrace-rs

**Comment by fitzgen** [comment]
We should cut a new release after this and the other PR merge.

**Comment by philipc** [comment]
Approved under the assumption that you've tested and it works. But the logic in that loop is convoluted, and it's not clear to me that there's no more holes in it. So I'll do another PR later today to clean that up.

> We should cut a new release after this and the other PR merge.

I consider #29 to be important to fix.

I have a fix based on converting it to use sequences. It's a lot slower, but correctness is better than speed. Otherwise I can do the change I described in https://github.com/gimli-rs/addr2line/issues/29#issuecomment-321959260, but I haven't started on that yet.

**Comment by philipc** [comment]
Oops, I didn't notice this failed the build.

**Comment by philipc** [comment]
So the failure is due to a bug in binutils addr2line. It tries to be too smart about handling non-increasing addresses within a sequence, and gets it wrong.

**Comment by fitzgen** [comment]
Huh. Tests were passing locally, I guess I have a different version of binutils on my machine.

**Pull request merged**
