### PR TITLE
Use cargo-tarpaulin instead of kcov

### PR DESCRIPTION
**Pull request by philipc**
Also stop use travis-cargo because it is unmaintained and no longer provides any benefit.

### CODE REVIEW

**Comment by philipc** [comment]
Still timed out...
Worked fine when I tested it here though: https://travis-ci.org/philipc/addr2line/builds/282569006

**Comment by jonhoo** [comment]
That's a little disturbing. It really shouldn't take that much longer from one run to the next on the same fixture.. Let me try restarting it.

**Comment by jonhoo** [comment]
@philipc hmm, the re-run also timed out (https://travis-ci.org/gimli-rs/addr2line/jobs/282572460). Tried restarting it a second time, but this suggests a deeper issue..

**Comment by philipc** [comment]
Did some investigating:
- the hang occurs locally too
- I've only seen it hang on the self tests
- when the hang occurs cpu usage goes to 0
- I've had the hang occur for normal testing (not doing code coverage)
- when the hang on the normal test occurred, I was able to ptrace and it was blocked on a futex

So, I don't think it's a travis problem or code coverage problem or timeout problem. I've added a commit to disable self tests for now. I don't think kcov was a problem, but I'd still like to switch to tarpaulin.

**Comment by philipc** [comment]
tarpaulin's coverage results don't make much sense, it seems a bit buggy. Still looking into it.

**Comment by jonhoo** [comment]
@philipc yeah, we've seen coverage drop with tarpaulin over at https://github.com/mattnenterprise/rust-imap/pull/46 too. But I agree we probably want to change.

**Comment by philipc** [comment]
tarpaulin's coverage has been improved, I'll try this again when there's a new release of it.

**Pull request closed without merging**
